
[package]
name = "wotail-api-tailscale"
version = "0.1.0"
edition = "2024"


[dependencies]
env = "1.0.1"
reqwest = { version = "0.12.23", features = ["json"] }
serde = "1.0.219"
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
